{% set version = "0.9.0" %}

package:
  name: openpmd_viewer
  version: {{ version }}

source:
  git_rev: {{ version }}
  git_url: https://github.com/openPMD/openPMD-viewer.git

build:
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy
    - scipy
    - matplotlib
    - h5py
  run:
    - python
    - cython
    - numpy
    - scipy
    - matplotlib
    - h5py
    - jupyter

test:
  imports:
    - opmd_viewer

about:
  home: https://github.com/openPMD/openPMD-viewer
  license: BSD-3-clause
  license_file: LICENSE.txt
  summary: "Visualization tools for openPMD files"
